#!/usr/bin/env bash
# install_hooks.sh — Install git pre-commit hooks.
#
# Two checks run in order, both blocking:
#   1. PII scanner — `scripts/pii_scan.py`
#   2. Data-lineage freshness — `docs/data-lineage/check_freshness.py`
#      (only triggers when a `docs/data-lineage/lineage/*.yaml` is staged)
#
# Run from repo root:
#   bash scripts/install_hooks.sh
#
# Idempotent: safe to re-run. If a non-managed pre-commit hook already
# exists, it is backed up to .git/hooks/pre-commit.bak before being
# replaced.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
HOOK_PATH="$REPO_ROOT/.git/hooks/pre-commit"

if [[ -f "$HOOK_PATH" && ! -L "$HOOK_PATH" ]]; then
  if ! grep -q "pii_scan.py" "$HOOK_PATH"; then
    cp "$HOOK_PATH" "$HOOK_PATH.bak"
    echo "install_hooks: backed up existing pre-commit to $HOOK_PATH.bak"
  fi
fi

cat > "$HOOK_PATH" <<'HOOK'
#!/usr/bin/env bash
# Auto-generated by scripts/install_hooks.sh
# Two checks, both blocking:
#   1. PII scan against staged files.
#   2. Data-lineage freshness — only if a lineage YAML is staged.
set -euo pipefail
REPO_ROOT="$(git rev-parse --show-toplevel)"

python "$REPO_ROOT/scripts/pii_scan.py"

if git diff --cached --name-only --diff-filter=ACMR \
     | grep -q '^docs/data-lineage/lineage/.*\.yaml$'; then
  echo "pre-commit: lineage/*.yaml staged — checking generated artifacts are fresh…"
  python "$REPO_ROOT/docs/data-lineage/check_freshness.py"
fi
HOOK

chmod +x "$HOOK_PATH"
echo "install_hooks: pre-commit hook installed at $HOOK_PATH"
echo "install_hooks: registered checks — pii_scan + lineage freshness (conditional)."
echo "install_hooks: test PII by staging a file containing a known last-4 and running 'git commit'."
echo "install_hooks: test lineage by editing a docs/data-lineage/lineage/*.yaml without regenerating."
