#!/usr/bin/env bash
# install_hooks.sh — Install git pre-commit + commit-msg + pre-push hooks.
#
# Five checks run in order on `git commit`:
#
#   pre-commit (blocking):
#     1. PII scan         — `scripts/pii_scan.py`
#     2. Lineage freshness — `docs/data-lineage/check_freshness.py`
#        Runs unconditionally; ~3 s.
#     3. Doc-coupling rules — staged code-paths force matching doc updates.
#        See `scripts/check_doc_coupling.py` for the rule list.
#     4. Action-item cross-ref rule — staged ACTION_ITEMS.md status
#        flips force matching lineage cross-ref updates. See
#        `scripts/check_action_item_refs.py`.
#
#   commit-msg (blocking):
#     5. Verified-task rule — `[v]` / "Verified" in the message must be
#        accompanied by a touch on ROADMAP.md or ROADMAP_ARCHIVE.md.
#
#   pre-push (non-blocking):
#     6. Graphify code-only AST refresh — runs
#        `tools/graphify/refresh_delta.py --code-only --no-commit` if the
#        graphify venv is reachable. Free, ~5s. Reminds you to commit if
#        the rolling snapshot drifted; never blocks the push. Skipped on
#        SKIP_GRAPHIFY_HOOK=1.
#
# Escape hatches (use deliberately, leave a trail):
#   - `SKIP_DOCS_CHECK="<reason>" git commit ...` skips checks 2–4.
#   - Commit-message trailer `Skip-Docs-Check: <reason>` skips check 5.
#   - `SKIP_GRAPHIFY_HOOK=1 git push` skips check 6.
#   - `git commit --no-verify` skips everything (agents must not).
#
# Run from repo root:  bash scripts/install_hooks.sh
# Idempotent. Existing non-managed hooks are backed up to *.bak.

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
PRE_COMMIT="$REPO_ROOT/.git/hooks/pre-commit"
COMMIT_MSG="$REPO_ROOT/.git/hooks/commit-msg"
PRE_PUSH="$REPO_ROOT/.git/hooks/pre-push"

backup_if_unmanaged() {
  local path="$1" marker="$2"
  if [[ -f "$path" && ! -L "$path" ]]; then
    if ! grep -q "$marker" "$path"; then
      cp "$path" "$path.bak"
      echo "install_hooks: backed up existing $(basename "$path") to $path.bak"
    fi
  fi
}

backup_if_unmanaged "$PRE_COMMIT" "pii_scan.py"
backup_if_unmanaged "$COMMIT_MSG" "Skip-Docs-Check"
backup_if_unmanaged "$PRE_PUSH" "refresh_delta.py"

# ----- pre-commit ----------------------------------------------------
cat > "$PRE_COMMIT" <<'HOOK'
#!/usr/bin/env bash
# Auto-generated by scripts/install_hooks.sh — do not edit by hand.
# Four blocking checks: PII scan, lineage freshness, doc-coupling,
# action-item cross-ref consistency.
set -euo pipefail
REPO_ROOT="$(git rev-parse --show-toplevel)"

python "$REPO_ROOT/scripts/pii_scan.py"

if [[ -n "${SKIP_DOCS_CHECK:-}" ]]; then
  echo "pre-commit: SKIP_DOCS_CHECK set (\"$SKIP_DOCS_CHECK\") — skipping freshness + coupling + ai-refs."
  exit 0
fi

# Lineage freshness — unconditional. Generators are deterministic; if
# the yaml-derived artifacts drift, regen them and re-stage.
echo "pre-commit: checking lineage freshness…"
python "$REPO_ROOT/docs/data-lineage/check_freshness.py"

# Doc-coupling — staged code paths force matching doc updates.
echo "pre-commit: checking doc-coupling rules…"
python "$REPO_ROOT/scripts/check_doc_coupling.py"

# Action-item cross-ref consistency — moving an AI-NNN between
# Open/Resolved must touch the lineage files that mention it.
echo "pre-commit: checking action-item cross-refs…"
python "$REPO_ROOT/scripts/check_action_item_refs.py"
HOOK
chmod +x "$PRE_COMMIT"

# ----- commit-msg ----------------------------------------------------
cat > "$COMMIT_MSG" <<'HOOK'
#!/usr/bin/env bash
# Auto-generated by scripts/install_hooks.sh — do not edit by hand.
# Verified-task rule: a message containing `[v]` or "Verified" must
# touch ROADMAP.md or ROADMAP_ARCHIVE.md.
#
# Bypass with a `Skip-Docs-Check: <reason>` trailer (one line, anywhere
# in the message). The `<reason>` is a free-form string for accountability.
set -euo pipefail
MSG_FILE="$1"
MSG="$(cat "$MSG_FILE")"

if echo "$MSG" | grep -qiE '^Skip-Docs-Check:'; then
  exit 0
fi

# Match `[v]` or the word Verified (case-insensitive, word-bounded).
if echo "$MSG" | grep -qE '\[v\]|[Vv]erified'; then
  STAGED="$(git diff --cached --name-only --diff-filter=ACMR)"
  if ! echo "$STAGED" | grep -qE '^docs/(ROADMAP\.md|ROADMAP_ARCHIVE\.md)$'; then
    cat >&2 <<'ERR'
commit-msg: ERROR — verified-task message but ROADMAP.md not touched.

The commit message indicates a task was verified ([v] or "Verified"),
but neither docs/ROADMAP.md nor docs/ROADMAP_ARCHIVE.md is in the
staged diff. Update the roadmap status and re-commit.

To bypass for genuinely-not-roadmap-tracked work, add a trailer:
  Skip-Docs-Check: <one-line reason>
ERR
    exit 1
  fi
fi
exit 0
HOOK
chmod +x "$COMMIT_MSG"

# ----- pre-push -------------------------------------------------------
cat > "$PRE_PUSH" <<'HOOK'
#!/usr/bin/env bash
# Auto-generated by scripts/install_hooks.sh — do not edit by hand.
# Non-blocking: runs the graphify code-only AST refresh and reminds the
# user if the rolling snapshot drifted. Never aborts the push.
#
# Bypass: SKIP_GRAPHIFY_HOOK=1 git push
set -uo pipefail
REPO_ROOT="$(git rev-parse --show-toplevel)"

if [[ -n "${SKIP_GRAPHIFY_HOOK:-}" ]]; then
  exit 0
fi

# Locate the graphify venv. The throwaway venv path is conventional; if
# it's missing or the script can't import graphify, just skip silently.
VENV_PY="$HOME/graphify-trial-2026-04-29/venv/Scripts/python.exe"
if [[ ! -x "$VENV_PY" ]]; then
  VENV_PY="$HOME/graphify-trial-2026-04-29/venv/bin/python"
fi
if [[ ! -x "$VENV_PY" ]]; then
  exit 0
fi

if ! "$VENV_PY" -c "import graphify" 2>/dev/null; then
  exit 0
fi

echo "pre-push: graphify code-only AST refresh (free, ~5s)..."
GRAPHIFY_PROJECT_ROOT="$REPO_ROOT" "$VENV_PY" \
  "$REPO_ROOT/tools/graphify/refresh_delta.py" \
  --code-only --no-commit --allow-dirty
status=$?

if [[ $status -eq 0 ]]; then
  echo "pre-push: graphify rolling snapshot updated under docs/audits/graphify-current/."
  echo "pre-push: review and commit it (or let the nightly task do it)."
elif [[ $status -eq 1 ]]; then
  : # no diff, nothing to do
else
  echo "pre-push: graphify refresh non-fatal warning (exit $status); push continuing."
fi
exit 0
HOOK
chmod +x "$PRE_PUSH"

echo "install_hooks: pre-commit + commit-msg + pre-push installed."
echo "install_hooks: registered checks —"
echo "  pre-commit:   pii_scan, lineage freshness, doc-coupling, action-item cross-refs"
echo "  commit-msg:   verified-task → ROADMAP touch"
echo "  pre-push:     graphify code-only AST refresh (non-blocking, free)"
echo "install_hooks: bypass via SKIP_DOCS_CHECK / SKIP_GRAPHIFY_HOOK envs or 'Skip-Docs-Check:' trailer."
